version: '3'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: circles-letsencrypt
    depends_on:
      - nginx
      - gen
    environment:
      - NGINX_PROXY_CONTAINER=circles-nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=circles-nginx-gen
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        - GIT_COMMIT=59dc09f
    container_name: circles-app
    environment:
      - VIRTUAL_HOST=${HOST_APP}
      - LETSENCRYPT_HOST=${HOST_APP}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
