version: '3'
services:
  indexer-db-init:
    build:
      dockerfile: indexer-db-init/Dockerfile
      context: .
    depends_on:
      - db
    environment:
      POSTGRES_HOST:  ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DATABASE_INDEXER_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
  
  blockchain-indexer:
    image: circlesubi/blockchain-indexer:dev
    expose:
      - 8675
    depends_on:
      - indexer-db-init
    restart: unless-stopped
    environment:
      INDEXER_WEBSOCKET_URL:     ${BLOCKCHAIN_INDEXER_WEBSOCKET_URL}
      INDEXER_RPC_GATEWAY_URL:   ${INTERNAL_CHAIN_RPC_URL}
      HUB_ADDRESS:               ${HUB_ADDRESS}
      INDEXER_CONNECTION_STRING: "Server=${POSTGRES_HOST};Port=5432;Database=${POSTGRES_DATABASE_INDEXER_DB};User ID=${POSTGRES_USER};Password=${POSTGRES_USER};Command Timeout=240"
    
  other-blockchain-user:
    restart: unless-stopped
    build:
      dockerfile: ${PWD}/other_chain_user/Dockerfile
      context: ${PWD}/other_chain_user
    environment:
      RPC_URL: ${INTERNAL_CHAIN_RPC_URL}
      TO_ADDRESS: '0x85a88313b37676ef7F846E00287090E75931E44B'
      PRIVATE_KEY: '0x8a49c61f64ed99f8a59a9bd62cd39238f7256beead025b86e25476e329637b93'

  pathfinder2-updater:
    depends_on:
      - pathfinder2
      - blockchain-indexer
    image: circlesubi/pathfinder2-updater:dev
    restart: unless-stopped
    environment:
      INDEXER_DB_CONNECTION_STRING: "Server=${POSTGRES_HOST};Port=5432;Database=${POSTGRES_DATABASE_INDEXER_DB};User ID=${POSTGRES_USER};Password=${POSTGRES_USER};Command Timeout=240"
      INDEXER_WS_URL:               ${INDEXER_WS_URL}
      INTERNAL_CAPACITY_GRAPH_PATH: ${INTERNAL_CAPACITY_GRAPH_PATH}
      EXTERNAL_CAPACITY_GRAPH_PATH: ${EXTERNAL_CAPACITY_GRAPH_PATH}
      PATHFINDER_RPC_URL:           ${PATHFINDER_RPC_URL}
    volumes:
      - ${PWD}/.state/pathfinder:/var/pathfinder2/data

  pathfinder2:
    image: circlesubi/pathfinder2:eeee335
    restart: unless-stopped
    expose:
      - "54389"
    command:
      - "0.0.0.0:54389"
    volumes:
      - ${PWD}/.state/pathfinder:/var/pathfinder2/data
 


  pathfinder-proxy:
    image: circlesubi/pathfinder-proxy:dev
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PORT: '8080'
      CORS_ORIGINS: 'https://circles.land'
      UPSTREAM_SERVICE_ENDPOINTS: 'http://pathfinder2:54389'
      UPSTREAM_HEALTH_ENDPOINTS: 'http://pathfinder2-updater:8794'