version: '3'

services:
  relayer-service: &relayer-service
    build: ../safe-relay-service
    volumes:
      - "../safe-relay-service/safe_relay_service:/safe-relay-service/safe_relay_service"

  relayer-worker: &relayer-worker
    <<: *relayer-service

  relayer-scheduler:
    <<: *relayer-worker

  api: &api
    build: ../circles-api
    volumes:
      - "../circles-api/src:/usr/src/app/src"

  api-worker:
    <<: *api
