version: '3'

volumes:
  relayer:
  relayer_html:

services:
  nginx:
    volumes:
      - relayer_html:/usr/share/nginx/html/relayer
      - ./relayer/nginx.conf:/etc/nginx/vhost.d/${HOST_RELAYER}

  relayer-service: &relayer-service
    image: joincircles/safe-relay-service:v4.1.9
    container_name: circles-relayer-service
    depends_on:
      - db
      - ganache
      - redis
    working_dir: /safe-relay-service
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${HOST_RELAYER}
      - GRAPH_NODE_ENDPOINT=http://graph:8000
      - RELAYER_REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - C_FORCE_ROOT=true
      - DJANGO_SECRET_KEY=development
      - DJANGO_SETTINGS_MODULE=config.settings.development
    volumes:
      - relayer:/nginx
      - relayer_html:/usr/share/nginx/html/relayer
    command: ./run.sh

  relayer-worker: &relayer-worker
    <<: *relayer-service
    container_name: circles-relayer-worker
    depends_on:
      - db
      - ganache
      - redis
      - relayer-service
    command: ./run-worker.sh

  relayer-scheduler:
    <<: *relayer-worker
    container_name: circles-relayer-scheduler
    command: ./run-scheduler.sh
