version: "3"

services:
  payment-api:
    image: joincircles/circles-payment-api:v1.1.0
    container_name: circles-payment-api
    ports:
      - 3002:3002
    env_file:
      - .env
    environment:
      PORT: 3002
      FASTIFY_LOG_LEVEL: info
      FUNDER_ACCOUNT_PRIVATE_KEY: ${PRIVATE_KEY_PAYMENT_API}
      RPC_URL: ${ETHEREUM_NODE_ENDPOINT}
      CORS_REGEX: ${MYXO_CORS_ORIGINS}
