version: '3'
services:
  pathfinder2:
    image: docker.io/circlesubi/pathfinder2:feature-dockerfile
    restart: unless-stopped
    expose:
      - "54389"
    command:
      - "0.0.0.0:54389"
    volumes:
      - ${PWD}/.state/pathfinder:/var/pathfinder2/data
 
  pathfinder2-updater:
    depends_on:
      - pathfinder2
    image: docker.io/circlesubi/pathfinder2-updater:dev
    restart: unless-stopped
    environment:
      INDEXER_DB_CONNECTION_STRING: "Server=${POSTGRES_HOST};Port=5432;Database=${POSTGRES_DATABASE_INDEXER_DB};User ID=${POSTGRES_USER};Password=${POSTGRES_USER};Command Timeout=240"
      INDEXER_WS_URL:               ${INDEXER_WS_URL}
      INTERNAL_CAPACITY_GRAPH_PATH: ${INTERNAL_CAPACITY_GRAPH_PATH}
      EXTERNAL_CAPACITY_GRAPH_PATH: ${EXTERNAL_CAPACITY_GRAPH_PATH}
      PATHFINDER_RPC_URL:           ${PATHFINDER_RPC_URL}
    volumes:
      - ${PWD}/.state/pathfinder:/var/pathfinder2/data

  blockchain-indexer:
    image: docker.io/circlesubi/blockchain-indexer:dev
    expose:
      - "8675"
    restart: unless-stopped
    environment:
      INDEXER_WEBSOCKET_URL:     ${INDEXER_WEBSOCKET_URL}
      INDEXER_RPC_GATEWAY_URL:   ${INDEXER_RPC_GATEWAY_URL}
      HUB_ADDRESS:               ${HUB_ADDRESS}
      INDEXER_CONNECTION_STRING: "Server=${POSTGRES_HOST};Port=5432;Database=${POSTGRES_DATABASE_INDEXER_DB};User ID=${POSTGRES_USER};Password=${POSTGRES_USER};Command Timeout=240"
  
  other-blockchain-user:
    restart: unless-stopped
    build:
      dockerfile: ${PWD}/other_chain_user/Dockerfile
      context: ${PWD}/other_chain_user
    depends_on:
      - ganache
    environment:
      RPC_URL: 'http://ganache:8545'
      TO_ADDRESS: '0x85a88313b37676ef7F846E00287090E75931E44B'
      PRIVATE_KEY: '0x8a49c61f64ed99f8a59a9bd62cd39238f7256beead025b86e25476e329637b93'


  indexer-db-init:
    build:
      dockerfile: indexer-db-init/Dockerfile
      context: .
    depends_on:
      - db
    environment:
      POSTGRES_HOST: 'indexer-db'
      POSTGRES_PORT: '5432'
      POSTGRES_DB: 'index'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'


  pathfinder-proxy:
    image: circlesubi/pathfinder-proxy:dev
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PORT: '8080'
      CORS_ORIGINS: 'https://circles.land'
      UPSTREAM_SERVICE_ENDPOINTS: 'http://pathfinder2:54389'
      UPSTREAM_HEALTH_ENDPOINTS: 'http://pathfinder2-updater:8794'